/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    offers: Offer;
    reviews: Review;
    media: Media;
    users: User;
    pageviews: Pageview;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pageviews: PageviewsSelect<false> | PageviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    appearance: Appearance;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Build new website pages by stacking layout blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  /**
   * Add a link to this page in the main navigation.
   */
  showInNav?: boolean | null;
  /**
   * Add, reorder and remove sections to compose the page.
   */
  layout?:
    | (
        | {
            kicker?: string | null;
            heading: string;
            subheading?: string | null;
            background?: (number | null) | Media;
            actions?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            kicker?: string | null;
            heading?: string | null;
            intro?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  href?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            source?: ('featured' | 'all') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviewsBlock';
          }
        | {
            heading?: string | null;
            type?: ('news' | 'blog' | 'commentary' | 'investigation' | 'any') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postsBlock';
          }
        | {
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'offersBlock';
          }
      )[]
    | null;
  /**
   * Overrides the title and description shown in search results.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos and files used across the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * News, blogs, commentary and investigative pieces.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  type: 'news' | 'blog' | 'commentary' | 'investigation';
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * Show this on the homepage.
   */
  featured?: boolean | null;
  author?: (number | null) | User;
  coverImage?: (number | null) | Media;
  /**
   * Short summary used in listings and link previews.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides the title and description shown in search results.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in to this dashboard.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Determines what this person can see and change.
   */
  role: 'admin' | 'editor' | 'author';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Promotions, packages and limited-time offers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published';
  /**
   * Short highlight, for example "20% off" or "New".
   */
  badge?: string | null;
  summary: string;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  startsAt?: string | null;
  /**
   * Leave blank for an ongoing offer.
   */
  endsAt?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Client testimonials shown on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  /**
   * Job title or organisation.
   */
  role?: string | null;
  rating: number;
  quote: string;
  avatar?: (number | null) | Media;
  /**
   * Only approved reviews appear on the site.
   */
  approved?: boolean | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Raw traffic log behind the dashboard statistics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews".
 */
export interface Pageview {
  id: number;
  path: string;
  referrer?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pageviews';
        value: number | Pageview;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  showInNav?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              kicker?: T;
              heading?: T;
              subheading?: T;
              background?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              kicker?: T;
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        reviewsBlock?:
          | T
          | {
              heading?: T;
              source?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        postsBlock?:
          | T
          | {
              heading?: T;
              type?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        offersBlock?:
          | T
          | {
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  status?: T;
  publishedAt?: T;
  featured?: T;
  author?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  badge?: T;
  summary?: T;
  details?: T;
  image?: T;
  startsAt?: T;
  endsAt?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  rating?: T;
  quote?: T;
  avatar?: T;
  approved?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews_select".
 */
export interface PageviewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * All the text and imagery on the front page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroKicker?: string | null;
  heroHeading: string;
  heroBody?: string | null;
  /**
   * Full-bleed background photograph.
   */
  heroImage?: (number | null) | Media;
  heroCtaLabel?: string | null;
  heroCtaHref?: string | null;
  /**
   * The ring of keywords under the hero.
   */
  brandPillars?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutEyebrow?: string | null;
  aboutHeading?: string | null;
  aboutQuote?: string | null;
  aboutBody?: string | null;
  aboutBodySecondary?: string | null;
  aboutCapabilities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  servicesKicker?: string | null;
  servicesHeading?: string | null;
  servicesIntro?: string | null;
  /**
   * Drag to reorder the service cards.
   */
  services?:
    | {
        name: string;
        icon?:
          | (
              | 'newspaper'
              | 'fileText'
              | 'messageSquare'
              | 'search'
              | 'camera'
              | 'film'
              | 'megaphone'
              | 'video'
              | 'aperture'
              | 'clapperboard'
              | 'scissors'
              | 'graduationCap'
            )
          | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  productionChip?: string | null;
  productionHeading?: string | null;
  productionBody?: string | null;
  productionCtaLabel?: string | null;
  sancharHeading?: string | null;
  sancharIntro?: string | null;
  sancharTopics?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reorder, add or remove the links in the navbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Drag to reorder. These appear left to right in the header.
   */
  items: {
    label: string;
    /**
     * Section anchor such as "#services", or a path such as "/about".
     */
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  cta?: {
    label?: string | null;
    href?: string | null;
    enabled?: boolean | null;
  };
  /**
   * The thin contact strip above the header.
   */
  showUtilityBar?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Website colours, typography and corner rounding.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  /**
   * Headings, header and footer.
   */
  primary: string;
  /**
   * Gradients and deep panels.
   */
  primaryRich: string;
  /**
   * Links and primary buttons.
   */
  secondary: string;
  /**
   * Highlights and call-to-action accents.
   */
  signal: string;
  warm: string;
  surface: string;
  surfaceAlt: string;
  ink: string;
  muted: string;
  line: string;
  radius?: number | null;
  headingFont?: ('hanken' | 'inter') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer columns, links and company blurb.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  about?: string | null;
  groups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to use "© <year> <company name> All Rights Reserved."
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company name, contact details and identity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName: string;
  shortName: string;
  /**
   * Shown in the logo mark.
   */
  initials: string;
  address: string;
  logo?: (number | null) | Media;
  email: string;
  vat?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  website?: string | null;
  websiteLabel?: string | null;
  rightSanchar?: string | null;
  rightSancharLabel?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroHeading?: T;
  heroBody?: T;
  heroImage?: T;
  heroCtaLabel?: T;
  heroCtaHref?: T;
  brandPillars?:
    | T
    | {
        label?: T;
        id?: T;
      };
  aboutEyebrow?: T;
  aboutHeading?: T;
  aboutQuote?: T;
  aboutBody?: T;
  aboutBodySecondary?: T;
  aboutCapabilities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  servicesKicker?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        name?: T;
        icon?: T;
        href?: T;
        id?: T;
      };
  productionChip?: T;
  productionHeading?: T;
  productionBody?: T;
  productionCtaLabel?: T;
  sancharHeading?: T;
  sancharIntro?: T;
  sancharTopics?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
      };
  showUtilityBar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  primary?: T;
  primaryRich?: T;
  secondary?: T;
  signal?: T;
  warm?: T;
  surface?: T;
  surfaceAlt?: T;
  ink?: T;
  muted?: T;
  line?: T;
  radius?: T;
  headingFont?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  shortName?: T;
  initials?: T;
  address?: T;
  logo?: T;
  email?: T;
  vat?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  website?: T;
  websiteLabel?: T;
  rightSanchar?: T;
  rightSancharLabel?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}