/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    services: Service;
    'service-categories': ServiceCategory;
    offers: Offer;
    reviews: Review;
    faqs: Faq;
    'social-responsibility': SocialResponsibility;
    team: Team;
    enquiries: Enquiry;
    media: Media;
    'media-slots': MediaSlot;
    redirects: Redirect;
    users: User;
    pageviews: Pageview;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'social-responsibility': SocialResponsibilitySelect<false> | SocialResponsibilitySelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'media-slots': MediaSlotsSelect<false> | MediaSlotsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    pageviews: PageviewsSelect<false> | PageviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    navigation: Navigation;
    announcement: Announcement;
    appearance: Appearance;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    announcement: AnnouncementSelect<false> | AnnouncementSelect<true>;
    appearance: AppearanceSelect<false> | AppearanceSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the website - Home, Services, Our Work, Contact, About and the rest. Open one to change its words and sections, build a new one, or take one off the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Shown in the menu and in breadcrumbs.
   */
  title: string;
  /**
   * A website page is one the site ships with; deleting it here restores the copy it shipped with. A new page is one built in the dashboard.
   */
  kind: 'route' | 'custom';
  /**
   * The address this page answers at. New pages take it from the slug below.
   */
  path?: string | null;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  /**
   * Publishing puts this on the website; a draft stays here.
   */
  status: 'draft' | 'published';
  /**
   * Add a link to this page in the main navigation.
   */
  showInNav?: boolean | null;
  /**
   * Position in the menu, left to right. Leave empty to place it after the numbered links.
   */
  navOrder?: number | null;
  /**
   * The address of the menu item this page sits under, for example "/our-work". The menu highlights that item while a visitor is here.
   */
  parent?: string | null;
  /**
   * One line describing the page. Shown on the dashboard's page list.
   */
  summary?: string | null;
  /**
   * Everything on the page, top to bottom. Add, reorder, rewrite or remove a section and the website follows.
   */
  layout?:
    | (
        | {
            /**
             * The line above the title.
             */
            eyebrow: string;
            heading: string;
            description?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            /**
             * Leave the address empty as well to send people to the Right Sanchar address in Site settings.
             */
            ctaExternal?: boolean | null;
            /**
             * Optional service category id (for example "production"), which colours the hero emblem.
             */
            category?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageHero';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            /**
             * The opening paragraph, set larger.
             */
            lead?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            linkLabel?: string | null;
            linkHref?: string | null;
            /**
             * A tinted band sets the section apart from the white ones around it.
             */
            tone?: ('plain' | 'tinted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prose';
          }
        | {
            /**
             * The quotation inside the panel. The company name and address come from Site settings.
             */
            panelQuote?: string | null;
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            lead?: string | null;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            linkLabel?: string | null;
            linkHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'identityStory';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            style: 'values' | 'disciplines' | 'topics' | 'links';
            tone?: ('plain' | 'tinted') | null;
            cards?:
              | {
                  /**
                   * Drawn above the title.
                   */
                  icon?:
                    | (
                        | 'camera'
                        | 'clapperboard'
                        | 'film'
                        | 'megaphone'
                        | 'newspaper'
                        | 'graduationCap'
                        | 'search'
                        | 'monitorSmartphone'
                        | 'speech'
                        | 'heartHandshake'
                        | 'bookOpen'
                        | 'users'
                        | 'userRoundPen'
                        | 'compass'
                        | 'calendarCheck'
                        | 'monitorPlay'
                        | 'radio'
                        | 'sparkles'
                        | 'layoutDashboard'
                        | 'smartphone'
                        | 'server'
                        | 'landmark'
                        | 'building2'
                        | 'globe2'
                        | 'mic2'
                      )
                    | null;
                  title: string;
                  text?: string | null;
                  /**
                   * Shown as a ticked list on the discipline style.
                   */
                  points?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  linkLabel?: string | null;
                  linkHref?: string | null;
                  id?: string | null;
                }[]
              | null;
            chips?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureCards';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            steps?:
              | {
                  title: string;
                  text: string;
                  id?: string | null;
                }[]
              | null;
            tone?: ('plain' | 'tinted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'processSteps';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            /**
             * Questions saved in Content → FAQs replace the list below: the ones published to this page, plus the ones published to the page named here. Leave this empty to use the questions published to this page, and the list below when there are none.
             */
            placement?:
              | (
                  | 'home'
                  | 'services'
                  | 'our-work'
                  | 'contact'
                  | 'about'
                  | 'production'
                  | 'social-media-handling'
                  | 'training'
                  | 'research'
                  | 'it'
                  | 'advertisement'
                  | 'right-sanchar'
                  | 'posts'
                  | 'offers'
                )
              | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            tone?: ('plain' | 'tinted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            source: 'category' | 'slugs' | 'all';
            /**
             * The category id, for example "production" or "training".
             */
            category?: string | null;
            slugs?:
              | {
                  slug: string;
                  id?: string | null;
                }[]
              | null;
            tone?: ('plain' | 'tinted') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceCards';
          }
        | {
            ariaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryBar';
          }
        | {
            /**
             * One section per category in Content → Service categories, listing the services filed under it.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'categoryGroups';
          }
        | {
            /**
             * The Page media entry to show, for example "about".
             */
            mediaKey: string;
            /**
             * Names the band: “<title> in pictures & film”.
             */
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaShowcase';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamSection';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'socialResponsibilitySection';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            /**
             * The line under the company name and VAT number.
             */
            note?: string | null;
            linkLabel?: string | null;
            linkHref?: string | null;
            showForm?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactDetails';
          }
        | {
            heading: string;
            description?: string | null;
            /**
             * Preselects this service on the contact form.
             */
            service?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactCta';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            body?: string | null;
            primaryLabel?: string | null;
            /**
             * Leave empty to use the Right Sanchar address from Site settings.
             */
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portalLinks';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            limit?: number | null;
            /**
             * Shown while nothing has been published.
             */
            emptyText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postList';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            limit?: number | null;
            /**
             * Shown while no offer is running.
             */
            emptyText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'offerList';
          }
        | {
            /**
             * The second button. Its address is the Right Sanchar link in Site settings. The words in this band are written in Site → Homepage & page copy, on the "Home - hero" tab.
             */
            secondaryLabel?: string | null;
            showMediaSystem?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            linkLabel?: string | null;
            linkHref?: string | null;
            /**
             * The caption on the visual. The words in this band are written in Site → Homepage & page copy, on the "Home - about" tab.
             */
            captionTitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeAbout';
          }
        | {
            /**
             * The words in this band are written in Site → Homepage & page copy, on the "Home - leadership" tab.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'leadershipSection';
          }
        | {
            /**
             * The words in this band are written in Site → Homepage & page copy, on the "Production page" tab.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productionBand';
          }
        | {
            /**
             * The words in this band are written in Site → Homepage & page copy, on the "Right Sanchar page" tab.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sancharBand';
          }
        | {
            /**
             * The words in this band are written in Site → Homepage & page copy, on the "Services page" tab.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBand';
          }
        | {
            /**
             * The small label above the heading.
             */
            kicker?: string | null;
            heading?: string | null;
            /**
             * One or two lines under the heading.
             */
            description?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'searchSection';
          }
        | {
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signupSection';
          }
        | {
            kicker?: string | null;
            heading: string;
            subheading?: string | null;
            background?: (number | null) | Media;
            actions?:
              | {
                  label: string;
                  href: string;
                  style?: ('primary' | 'secondary') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            kicker?: string | null;
            heading?: string | null;
            intro?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  href?: string | null;
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardGrid';
          }
        | {
            heading?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            source?: ('featured' | 'all') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviewsBlock';
          }
        | {
            heading?: string | null;
            type?: ('news' | 'blog' | 'commentary' | 'investigation' | 'any') | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'postsBlock';
          }
        | {
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'offersBlock';
          }
      )[]
    | null;
  /**
   * Overrides the title and description shown in search results.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    /**
     * The page stays on the website and keeps working. It asks not to be indexed, and it leaves the sitemap.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every photograph, film and file on the website. Upload once here, then use it anywhere.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the picture or film for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional photographer or source credit.
   */
  credit?: string | null;
  /**
   * Choose the pages this photograph or film is published on. It joins the “in pictures & film” band on each of them. Leave it empty and the file is only used where something else points at it.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * News, blogs, commentary and investigative pieces. Published ones appear at /posts, newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  type: 'news' | 'blog' | 'commentary' | 'investigation';
  /**
   * Publishing puts this on the website; a draft stays here.
   */
  status: 'draft' | 'published';
  /**
   * Choose the pages this post is published on. Leave it empty to show it on every page that lists writing.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  /**
   * Optional. The post stays hidden until this time.
   */
  publishAt?: string | null;
  /**
   * Optional. The post disappears from the site after this time.
   */
  unpublishAt?: string | null;
  publishedAt?: string | null;
  /**
   * Show this on the homepage.
   */
  featured?: boolean | null;
  author?: (number | null) | User;
  /**
   * Shown at the top of the post and in link previews.
   */
  coverImage?: (number | null) | Media;
  /**
   * One or two sentences. Used in listings, search results and link previews.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional. Used for grouping and for search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Overrides the title and description shown in search results.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * People who can sign in to this dashboard. A new sign-up waits here until an administrator approves it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Determines what this person can see and change.
   */
  role: 'admin' | 'editor' | 'author';
  /**
   * Until this is ticked, the account cannot sign in.
   */
  approved?: boolean | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Everything the company offers, one document per service. Each published one gets its own page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used on cards and in breadcrumbs.
   */
  shortTitle: string;
  /**
   * One or two sentences, shown on cards and in the page header.
   */
  description: string;
  image?: (number | null) | Media;
  intro: string;
  audience?: string | null;
  preparation?: string | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Search-result description for this service page.
   */
  metaDescription?: string | null;
  /**
   * Overrides the title and description shown in search results.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  /**
   * Publishing puts this on the website; a draft stays here.
   */
  status: 'draft' | 'published';
  category: number | ServiceCategory;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Highlight on the homepage grid.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The sections the services page is grouped into.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  /**
   * Short name, e.g. "Production".
   */
  label: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  /**
   * Heading shown above this group.
   */
  title: string;
  description?: string | null;
  /**
   * Where "explore" links point, e.g. "/production".
   */
  href?: string | null;
  icon?: ('clapperboard' | 'megaphone' | 'graduationCap' | 'search' | 'camera' | 'newspaper') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Promotions, packages and limited-time offers. A published offer inside its dates appears at /offers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Leave blank to generate this from the title.
   */
  slug?: string | null;
  /**
   * Publishing puts this on the website; a draft stays here.
   */
  status: 'draft' | 'published';
  /**
   * Choose the pages this offer is published on. Leave it empty to show it on every page that lists offers.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  /**
   * Optional. The offer stays hidden until this time.
   */
  publishAt?: string | null;
  /**
   * Optional. The offer disappears from the site after this time.
   */
  unpublishAt?: string | null;
  /**
   * Short highlight, for example "20% off" or "New".
   */
  badge?: string | null;
  summary: string;
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  startsAt?: string | null;
  /**
   * Leave blank for an ongoing offer.
   */
  endsAt?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Client testimonials. Nothing here reaches the website until it is approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  /**
   * Job title or organisation.
   */
  role?: string | null;
  /**
   * Out of five.
   */
  rating: number;
  quote: string;
  avatar?: (number | null) | Media;
  /**
   * Only approved reviews appear on the site.
   */
  approved?: boolean | null;
  /**
   * Show this one first.
   */
  featured?: boolean | null;
  /**
   * Choose the pages this review is published on. Leave it empty to show it on every page that carries a reviews band.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Questions and answers. Each one picks the pages it belongs to, and search engines can show them as rich results.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Choose the pages this question is published on. Leave it empty to show it on every page that carries a questions band.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Films and photo albums from our social responsibility work, shown together on /our-work.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-responsibility".
 */
export interface SocialResponsibility {
  id: number;
  title: string;
  /**
   * A short description shown under the title.
   */
  summary?: string | null;
  /**
   * Paste the YouTube link, for example https://www.youtube.com/watch?v=XXXXXXXXXXX. Leave blank for a photo-only album.
   */
  youtubeUrl?: string | null;
  /**
   * Upload as many photographs as you like and drag to reorder them.
   */
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  date?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Publishing puts this on the website; a draft stays here.
   */
  status: 'draft' | 'published';
  /**
   * Choose the pages this entry is published on. Leave it empty to show it on every page that carries a social responsibility band.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The people introduced on the about page, in the order set here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  /**
   * Their title, as it should read on the page.
   */
  role: string;
  /**
   * Optional. One or two sentences.
   */
  bio?: string | null;
  photo?: (number | null) | Media;
  email?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Choose the pages this person is published on. Leave it empty to show it on every page that carries a team band.
   */
  placements?:
    | (
        | 'home'
        | 'services'
        | 'our-work'
        | 'contact'
        | 'about'
        | 'production'
        | 'social-media-handling'
        | 'training'
        | 'research'
        | 'it'
        | 'advertisement'
        | 'right-sanchar'
        | 'posts'
        | 'offers'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages sent through the website contact form. Private: nothing here is ever published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * The service the visitor was looking at when they wrote in.
   */
  service?: string | null;
  message: string;
  /**
   * Where this message has got to.
   */
  state?: ('new' | 'in-progress' | 'replied' | 'closed' | 'spam') | null;
  /**
   * Whoever is answering this one.
   */
  assignedTo?: (number | null) | User;
  /**
   * For the team only. Never shown on the website and never sent to the sender.
   */
  notes?: string | null;
  /**
   * The page the enquiry was sent from.
   */
  sourcePath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The photograph or film featured on each page. Open a row, upload a picture or a film, and save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-slots".
 */
export interface MediaSlot {
  id: number;
  /**
   * Which placeholder this fills: "home" (/), "home-about" (/), "services" (/services), "our-work" (/our-work), "contact" (/contact), "about" (/about), "production" (/production), "production-band" (/production), "social-media-handling" (/social-media-handling), "training" (/training), "research" (/research), "it" (/it), "advertisement" (/advertisement), "right-sanchar" (/right-sanchar), or a service slug such as "documentary-film-production" for a service page.
   */
  key: string;
  /**
   * Replaces the blue photo placeholder on this page.
   */
  image?: (number | null) | Media;
  /**
   * Printed under the photograph. Optional.
   */
  caption?: string | null;
  /**
   * Fill in one of the three sources below. An uploaded file is used first, then a YouTube link, then an address.
   */
  video?: {
    /**
     * An MP4 or WebM file. Large films are better published on YouTube and linked below - a host usually caps how much can be uploaded in one request.
     */
    file?: (number | null) | Media;
    /**
     * Paste an ordinary watch or share link.
     */
    youtubeUrl?: string | null;
    /**
     * The address of a film hosted somewhere else.
     */
    src?: string | null;
    /**
     * Shown before the film is played. Optional.
     */
    posterImage?: (number | null) | Media;
    /**
     * Only needed when the still is hosted elsewhere.
     */
    poster?: string | null;
    title?: string | null;
    description?: string | null;
    /**
     * What is said in the film, as readable text. Helps search engines.
     */
    transcript?: string | null;
    /**
     * ISO 8601, e.g. "PT2M30S".
     */
    duration?: string | null;
    uploadDate?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old address to a new one, so a link published elsewhere keeps working.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The old path, starting with "/", e.g. "/old-services".
   */
  from: string;
  /**
   * Where to send it: a path such as "/services", or a full URL.
   */
  to: string;
  /**
   * Permanent (301) tells search engines the move is final.
   */
  permanent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The raw traffic log behind the dashboard overview. No cookies, no personal data, no third party.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews".
 */
export interface Pageview {
  id: number;
  path: string;
  referrer?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'social-responsibility';
        value: number | SocialResponsibility;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'media-slots';
        value: number | MediaSlot;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pageviews';
        value: number | Pageview;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  path?: T;
  slug?: T;
  status?: T;
  showInNav?: T;
  navOrder?: T;
  parent?: T;
  summary?: T;
  layout?:
    | T
    | {
        pageHero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              ctaLabel?: T;
              ctaHref?: T;
              ctaExternal?: T;
              category?: T;
              id?: T;
              blockName?: T;
            };
        prose?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              lead?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              linkLabel?: T;
              linkHref?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        identityStory?:
          | T
          | {
              panelQuote?: T;
              kicker?: T;
              heading?: T;
              description?: T;
              lead?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              linkLabel?: T;
              linkHref?: T;
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              style?: T;
              tone?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    points?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    linkLabel?: T;
                    linkHref?: T;
                    id?: T;
                  };
              chips?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        processSteps?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              placement?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        serviceCards?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              source?: T;
              category?: T;
              slugs?:
                | T
                | {
                    slug?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        categoryBar?:
          | T
          | {
              ariaLabel?: T;
              id?: T;
              blockName?: T;
            };
        categoryGroups?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        mediaShowcase?:
          | T
          | {
              mediaKey?: T;
              heading?: T;
              id?: T;
              blockName?: T;
            };
        teamSection?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        socialResponsibilitySection?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              note?: T;
              linkLabel?: T;
              linkHref?: T;
              showForm?: T;
              id?: T;
              blockName?: T;
            };
        contactCta?:
          | T
          | {
              heading?: T;
              description?: T;
              service?: T;
              id?: T;
              blockName?: T;
            };
        portalLinks?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              body?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        postList?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              limit?: T;
              emptyText?: T;
              id?: T;
              blockName?: T;
            };
        offerList?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              limit?: T;
              emptyText?: T;
              id?: T;
              blockName?: T;
            };
        homeHero?:
          | T
          | {
              secondaryLabel?: T;
              showMediaSystem?: T;
              id?: T;
              blockName?: T;
            };
        homeAbout?:
          | T
          | {
              linkLabel?: T;
              linkHref?: T;
              captionTitle?: T;
              id?: T;
              blockName?: T;
            };
        leadershipSection?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        productionBand?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        sancharBand?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        servicesBand?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        searchSection?:
          | T
          | {
              kicker?: T;
              heading?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        signupSection?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              kicker?: T;
              heading?: T;
              subheading?: T;
              background?: T;
              actions?:
                | T
                | {
                    label?: T;
                    href?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        cardGrid?:
          | T
          | {
              kicker?: T;
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    href?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
        reviewsBlock?:
          | T
          | {
              heading?: T;
              source?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        postsBlock?:
          | T
          | {
              heading?: T;
              type?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        offersBlock?:
          | T
          | {
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  status?: T;
  placements?: T;
  publishAt?: T;
  unpublishAt?: T;
  publishedAt?: T;
  featured?: T;
  author?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  description?: T;
  image?: T;
  intro?: T;
  audience?: T;
  preparation?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaDescription?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  status?: T;
  category?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  title?: T;
  description?: T;
  href?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  placements?: T;
  publishAt?: T;
  unpublishAt?: T;
  badge?: T;
  summary?: T;
  details?: T;
  image?: T;
  startsAt?: T;
  endsAt?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  rating?: T;
  quote?: T;
  avatar?: T;
  approved?: T;
  featured?: T;
  placements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  placements?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-responsibility_select".
 */
export interface SocialResponsibilitySelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  youtubeUrl?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  date?: T;
  order?: T;
  status?: T;
  placements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  email?: T;
  order?: T;
  placements?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  state?: T;
  assignedTo?: T;
  notes?: T;
  sourcePath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  placements?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-slots_select".
 */
export interface MediaSlotsSelect<T extends boolean = true> {
  key?: T;
  image?: T;
  caption?: T;
  video?:
    | T
    | {
        file?: T;
        youtubeUrl?: T;
        src?: T;
        posterImage?: T;
        poster?: T;
        title?: T;
        description?: T;
        transcript?: T;
        duration?: T;
        uploadDate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  approved?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageviews_select".
 */
export interface PageviewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  device?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Written copy for the front page and for three pages that grew out of it. Each tab says which address it appears at.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroKicker?: string | null;
  heroHeading: string;
  heroBody?: string | null;
  /**
   * Full-bleed background photograph.
   */
  heroImage?: (number | null) | Media;
  heroCtaLabel?: string | null;
  heroCtaHref?: string | null;
  /**
   * The ring of keywords under the hero.
   */
  brandPillars?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  aboutEyebrow?: string | null;
  aboutHeading?: string | null;
  aboutQuote?: string | null;
  aboutBody?: string | null;
  aboutBodySecondary?: string | null;
  aboutCapabilities?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  leadershipKicker?: string | null;
  leadershipHeading?: string | null;
  /**
   * Shown one at a time on the homepage. The carousel moves on every five seconds, and visitors can step through with the arrows.
   */
  leadershipMessages?:
    | {
        role: string;
        name: string;
        heading?: string | null;
        message: string;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  servicesKicker?: string | null;
  servicesHeading?: string | null;
  servicesIntro?: string | null;
  /**
   * Drag to reorder the service cards.
   */
  services?:
    | {
        name: string;
        icon?:
          | (
              | 'newspaper'
              | 'fileText'
              | 'messageSquare'
              | 'search'
              | 'camera'
              | 'film'
              | 'megaphone'
              | 'video'
              | 'aperture'
              | 'clapperboard'
              | 'scissors'
              | 'graduationCap'
            )
          | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  productionChip?: string | null;
  productionHeading?: string | null;
  productionBody?: string | null;
  productionCtaLabel?: string | null;
  sancharHeading?: string | null;
  sancharIntro?: string | null;
  sancharTopics?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reorder, add or remove the links in the navbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Drag to reorder. These appear left to right in the header.
   */
  items: {
    label: string;
    /**
     * A path such as "/about", or a full address for another website. Every page this site has is listed on the dashboard home.
     */
    href: string;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  /**
   * The one filled button at the right of the header.
   */
  cta?: {
    label?: string | null;
    href?: string | null;
    enabled?: boolean | null;
  };
  /**
   * The thin line of phone, email and address above the header.
   */
  showUtilityBar?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * A strip above the header, for a campaign or a notice. Switch it on, or give it dates and let it appear and disappear on its own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement".
 */
export interface Announcement {
  id: number;
  /**
   * Nothing appears on the website until this is ticked.
   */
  enabled?: boolean | null;
  /**
   * One sentence. It is read before anything else on the page.
   */
  message?: string | null;
  linkLabel?: string | null;
  linkHref?: string | null;
  /**
   * Leave blank to show immediately.
   */
  startsAt?: string | null;
  /**
   * Leave blank to show until switched off.
   */
  endsAt?: string | null;
  /**
   * How loud the strip should look.
   */
  tone?: ('info' | 'highlight' | 'urgent') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Website colours, typography and corner rounding.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance".
 */
export interface Appearance {
  id: number;
  /**
   * Headings, header and footer.
   */
  primary: string;
  /**
   * Gradients and deep panels.
   */
  primaryRich: string;
  /**
   * Links and primary buttons.
   */
  secondary: string;
  /**
   * Highlights and call-to-action accents.
   */
  signal: string;
  warm: string;
  surface: string;
  surfaceAlt: string;
  ink: string;
  muted: string;
  line: string;
  radius?: number | null;
  headingFont?: ('hanken' | 'inter') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The columns of links and the company line at the foot of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * The paragraph in the first footer column. Two or three lines reads best.
   */
  about?: string | null;
  /**
   * Each one is a column in the footer, in the order listed here.
   */
  groups?:
    | {
        /**
         * The heading above the column.
         */
        title: string;
        links?:
          | {
              label: string;
              /**
               * A path such as "/services", or a full address.
               */
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to use "© <year> <company name> All Rights Reserved."
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Company name, contact details and identity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  legalName: string;
  shortName: string;
  /**
   * Shown in the logo mark.
   */
  initials: string;
  address: string;
  /**
   * Replaces the initials mark in the header, the media system wheel and the footer.
   */
  logo?: (number | null) | Media;
  email: string;
  vat?: string | null;
  /**
   * Shown in the order listed here.
   */
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  website?: string | null;
  /**
   * How the address is written out.
   */
  websiteLabel?: string | null;
  rightSanchar?: string | null;
  rightSancharLabel?: string | null;
  /**
   * For example "Facebook" and the page's address.
   */
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used when a page has no picture of its own. Landscape works best.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroHeading?: T;
  heroBody?: T;
  heroImage?: T;
  heroCtaLabel?: T;
  heroCtaHref?: T;
  brandPillars?:
    | T
    | {
        label?: T;
        id?: T;
      };
  aboutEyebrow?: T;
  aboutHeading?: T;
  aboutQuote?: T;
  aboutBody?: T;
  aboutBodySecondary?: T;
  aboutCapabilities?:
    | T
    | {
        label?: T;
        id?: T;
      };
  leadershipKicker?: T;
  leadershipHeading?: T;
  leadershipMessages?:
    | T
    | {
        role?: T;
        name?: T;
        heading?: T;
        message?: T;
        photo?: T;
        id?: T;
      };
  servicesKicker?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        name?: T;
        icon?: T;
        href?: T;
        id?: T;
      };
  productionChip?: T;
  productionHeading?: T;
  productionBody?: T;
  productionCtaLabel?: T;
  sancharHeading?: T;
  sancharIntro?: T;
  sancharTopics?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        newTab?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
      };
  showUtilityBar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement_select".
 */
export interface AnnouncementSelect<T extends boolean = true> {
  enabled?: T;
  message?: T;
  linkLabel?: T;
  linkHref?: T;
  startsAt?: T;
  endsAt?: T;
  tone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appearance_select".
 */
export interface AppearanceSelect<T extends boolean = true> {
  primary?: T;
  primaryRich?: T;
  secondary?: T;
  signal?: T;
  warm?: T;
  surface?: T;
  surfaceAlt?: T;
  ink?: T;
  muted?: T;
  line?: T;
  radius?: T;
  headingFont?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  about?: T;
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  legalName?: T;
  shortName?: T;
  initials?: T;
  address?: T;
  logo?: T;
  email?: T;
  vat?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  website?: T;
  websiteLabel?: T;
  rightSanchar?: T;
  rightSancharLabel?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}