import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * The table the daily backups are kept in.
 *
 * Generated by `payload migrate:create`, with two things added by hand: row
 * level security on the new table, the way every other table of this CMS is
 * secured, and `IF EXISTS` on the rollback's DROP CONSTRAINT - the statement
 * above it drops "backups" with CASCADE, which takes that foreign key with it,
 * so dropping it again by name would fail and leave the rollback stuck.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_backups_reason" AS ENUM('daily', 'manual', 'beforeRestore');
  CREATE TABLE "backups" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"label" varchar NOT NULL,
  	"taken_at" timestamp(3) with time zone NOT NULL,
  	"reason" "enum_backups_reason" DEFAULT 'daily' NOT NULL,
  	"summary" varchar,
  	"documents" numeric,
  	"problems" varchar,
  	"data" jsonb NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "backups_id" integer;
  CREATE INDEX "backups_taken_at_idx" ON "backups" USING btree ("taken_at");
  CREATE INDEX "backups_reason_idx" ON "backups" USING btree ("reason");
  CREATE INDEX "backups_updated_at_idx" ON "backups" USING btree ("updated_at");
  CREATE INDEX "backups_created_at_idx" ON "backups" USING btree ("created_at");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_backups_fk" FOREIGN KEY ("backups_id") REFERENCES "public"."backups"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_backups_id_idx" ON "payload_locked_documents_rels" USING btree ("backups_id");`)

  // A backup holds every enquiry the site has ever received, so this table is
  // locked down the moment it exists rather than in a migration after it.
  await db.execute(sql.raw(`ALTER TABLE "public"."backups" ENABLE ROW LEVEL SECURITY`));
  for (const role of ["anon", "authenticated"]) {
    await db.execute(sql.raw(`
      DO $$ BEGIN
        IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${role}') THEN
          REVOKE ALL ON TABLE "public"."backups" FROM "${role}";
        END IF;
      END $$;
    `));
  }
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "backups" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "backups" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_backups_fk";
  
  DROP INDEX "payload_locked_documents_rels_backups_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "backups_id";
  DROP TYPE "public"."enum_backups_reason";`)
}
