import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Generated by `payload migrate:create`, with one word added by hand: the
 * rollback's `DROP CONSTRAINT` on payload_locked_documents_rels is `IF EXISTS`.
 * The statement above it drops "social_work" with CASCADE, which takes that
 * foreign key with it, so dropping it again by name failed and left the whole
 * rollback stuck.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_partner_marquee_tone" AS ENUM('plain', 'tinted');
  CREATE TYPE "public"."enum__pages_v_blocks_partner_marquee_tone" AS ENUM('plain', 'tinted');
  CREATE TYPE "public"."enum_social_work_placements" AS ENUM('home', 'services', 'our-work', 'social-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  CREATE TYPE "public"."enum_social_work_status" AS ENUM('draft', 'published');
  ALTER TYPE "public"."enum_pages_blocks_faq_section_placement" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum__pages_v_blocks_faq_section_placement" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_posts_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum__posts_v_version_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_offers_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum__offers_v_version_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_reviews_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_faqs_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_social_responsibility_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_team_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_well_wishers_placements" ADD VALUE 'social-work' BEFORE 'contact';
  ALTER TYPE "public"."enum_media_placements" ADD VALUE 'social-work' BEFORE 'contact';
  CREATE TABLE "pages_blocks_partner_marquee_partners" (
  	"_order" integer NOT NULL,
  	"_parent_id" varchar NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"name" varchar,
  	"logo_id" integer,
  	"href" varchar
  );
  
  CREATE TABLE "pages_blocks_partner_marquee" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"heading" varchar DEFAULT 'We worked with',
  	"tone" "enum_pages_blocks_partner_marquee_tone" DEFAULT 'tinted',
  	"block_name" varchar
  );
  
  CREATE TABLE "pages_blocks_social_work_section" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"kicker" varchar,
  	"heading" varchar,
  	"description" varchar,
  	"empty_note" varchar,
  	"block_name" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_partner_marquee_partners" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"name" varchar,
  	"logo_id" integer,
  	"href" varchar,
  	"_uuid" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_partner_marquee" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar DEFAULT 'We worked with',
  	"tone" "enum__pages_v_blocks_partner_marquee_tone" DEFAULT 'tinted',
  	"_uuid" varchar,
  	"block_name" varchar
  );
  
  CREATE TABLE "_pages_v_blocks_social_work_section" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"_path" text NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"kicker" varchar,
  	"heading" varchar,
  	"description" varchar,
  	"empty_note" varchar,
  	"_uuid" varchar,
  	"block_name" varchar
  );
  
  CREATE TABLE "social_work_photos" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"image_id" integer NOT NULL,
  	"caption" varchar
  );
  
  CREATE TABLE "social_work_videos" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"youtube_url" varchar NOT NULL,
  	"title" varchar,
  	"description" varchar
  );
  
  CREATE TABLE "social_work_placements" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_social_work_placements",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "social_work" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"title" varchar NOT NULL,
  	"description" varchar,
  	"cover_image_id" integer,
  	"date" timestamp(3) with time zone,
  	"order" numeric DEFAULT 0,
  	"status" "enum_social_work_status" DEFAULT 'draft' NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "homepage_about_paragraphs" (
  	"_order" integer NOT NULL,
  	"_parent_id" integer NOT NULL,
  	"id" varchar PRIMARY KEY NOT NULL,
  	"text" varchar NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "social_work_id" integer;
  ALTER TABLE "appearance" ADD COLUMN "nepali_font_family" varchar DEFAULT 'Akriti';
  ALTER TABLE "appearance" ADD COLUMN "nepali_font_url" varchar DEFAULT 'https://fonts.cdnfonts.com/css/akriti';
  ALTER TABLE "pages_blocks_partner_marquee_partners" ADD CONSTRAINT "pages_blocks_partner_marquee_partners_logo_id_media_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_blocks_partner_marquee_partners" ADD CONSTRAINT "pages_blocks_partner_marquee_partners_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_partner_marquee"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_blocks_partner_marquee" ADD CONSTRAINT "pages_blocks_partner_marquee_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "pages_blocks_social_work_section" ADD CONSTRAINT "pages_blocks_social_work_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_partner_marquee_partners" ADD CONSTRAINT "_pages_v_blocks_partner_marquee_partners_logo_id_media_id_fk" FOREIGN KEY ("logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_partner_marquee_partners" ADD CONSTRAINT "_pages_v_blocks_partner_marquee_partners_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_partner_marquee"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_partner_marquee" ADD CONSTRAINT "_pages_v_blocks_partner_marquee_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_social_work_section" ADD CONSTRAINT "_pages_v_blocks_social_work_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "social_work_photos" ADD CONSTRAINT "social_work_photos_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "social_work_photos" ADD CONSTRAINT "social_work_photos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."social_work"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "social_work_videos" ADD CONSTRAINT "social_work_videos_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."social_work"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "social_work_placements" ADD CONSTRAINT "social_work_placements_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."social_work"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "social_work" ADD CONSTRAINT "social_work_cover_image_id_media_id_fk" FOREIGN KEY ("cover_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "homepage_about_paragraphs" ADD CONSTRAINT "homepage_about_paragraphs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."homepage"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_blocks_partner_marquee_partners_order_idx" ON "pages_blocks_partner_marquee_partners" USING btree ("_order");
  CREATE INDEX "pages_blocks_partner_marquee_partners_parent_id_idx" ON "pages_blocks_partner_marquee_partners" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_partner_marquee_partners_logo_idx" ON "pages_blocks_partner_marquee_partners" USING btree ("logo_id");
  CREATE INDEX "pages_blocks_partner_marquee_order_idx" ON "pages_blocks_partner_marquee" USING btree ("_order");
  CREATE INDEX "pages_blocks_partner_marquee_parent_id_idx" ON "pages_blocks_partner_marquee" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_partner_marquee_path_idx" ON "pages_blocks_partner_marquee" USING btree ("_path");
  CREATE INDEX "pages_blocks_social_work_section_order_idx" ON "pages_blocks_social_work_section" USING btree ("_order");
  CREATE INDEX "pages_blocks_social_work_section_parent_id_idx" ON "pages_blocks_social_work_section" USING btree ("_parent_id");
  CREATE INDEX "pages_blocks_social_work_section_path_idx" ON "pages_blocks_social_work_section" USING btree ("_path");
  CREATE INDEX "_pages_v_blocks_partner_marquee_partners_order_idx" ON "_pages_v_blocks_partner_marquee_partners" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_partner_marquee_partners_parent_id_idx" ON "_pages_v_blocks_partner_marquee_partners" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_partner_marquee_partners_logo_idx" ON "_pages_v_blocks_partner_marquee_partners" USING btree ("logo_id");
  CREATE INDEX "_pages_v_blocks_partner_marquee_order_idx" ON "_pages_v_blocks_partner_marquee" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_partner_marquee_parent_id_idx" ON "_pages_v_blocks_partner_marquee" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_partner_marquee_path_idx" ON "_pages_v_blocks_partner_marquee" USING btree ("_path");
  CREATE INDEX "_pages_v_blocks_social_work_section_order_idx" ON "_pages_v_blocks_social_work_section" USING btree ("_order");
  CREATE INDEX "_pages_v_blocks_social_work_section_parent_id_idx" ON "_pages_v_blocks_social_work_section" USING btree ("_parent_id");
  CREATE INDEX "_pages_v_blocks_social_work_section_path_idx" ON "_pages_v_blocks_social_work_section" USING btree ("_path");
  CREATE INDEX "social_work_photos_order_idx" ON "social_work_photos" USING btree ("_order");
  CREATE INDEX "social_work_photos_parent_id_idx" ON "social_work_photos" USING btree ("_parent_id");
  CREATE INDEX "social_work_photos_image_idx" ON "social_work_photos" USING btree ("image_id");
  CREATE INDEX "social_work_videos_order_idx" ON "social_work_videos" USING btree ("_order");
  CREATE INDEX "social_work_videos_parent_id_idx" ON "social_work_videos" USING btree ("_parent_id");
  CREATE INDEX "social_work_placements_order_idx" ON "social_work_placements" USING btree ("order");
  CREATE INDEX "social_work_placements_parent_idx" ON "social_work_placements" USING btree ("parent_id");
  CREATE INDEX "social_work_placements_value_idx" ON "social_work_placements" USING btree ("value");
  CREATE INDEX "social_work_cover_image_idx" ON "social_work" USING btree ("cover_image_id");
  CREATE INDEX "social_work_status_idx" ON "social_work" USING btree ("status");
  CREATE INDEX "social_work_updated_at_idx" ON "social_work" USING btree ("updated_at");
  CREATE INDEX "social_work_created_at_idx" ON "social_work" USING btree ("created_at");
  CREATE INDEX "homepage_about_paragraphs_order_idx" ON "homepage_about_paragraphs" USING btree ("_order");
  CREATE INDEX "homepage_about_paragraphs_parent_id_idx" ON "homepage_about_paragraphs" USING btree ("_parent_id");
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_social_work_fk" FOREIGN KEY ("social_work_id") REFERENCES "public"."social_work"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "payload_locked_documents_rels_social_work_id_idx" ON "payload_locked_documents_rels" USING btree ("social_work_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_partner_marquee_partners" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_partner_marquee" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "pages_blocks_social_work_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_partner_marquee_partners" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_partner_marquee" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_pages_v_blocks_social_work_section" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "social_work_photos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "social_work_videos" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "social_work_placements" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "social_work" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "homepage_about_paragraphs" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "pages_blocks_partner_marquee_partners" CASCADE;
  DROP TABLE "pages_blocks_partner_marquee" CASCADE;
  DROP TABLE "pages_blocks_social_work_section" CASCADE;
  DROP TABLE "_pages_v_blocks_partner_marquee_partners" CASCADE;
  DROP TABLE "_pages_v_blocks_partner_marquee" CASCADE;
  DROP TABLE "_pages_v_blocks_social_work_section" CASCADE;
  DROP TABLE "social_work_photos" CASCADE;
  DROP TABLE "social_work_videos" CASCADE;
  DROP TABLE "social_work_placements" CASCADE;
  DROP TABLE "social_work" CASCADE;
  DROP TABLE "homepage_about_paragraphs" CASCADE;
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT IF EXISTS "payload_locked_documents_rels_social_work_fk";
  
  ALTER TABLE "pages_blocks_faq_section" ALTER COLUMN "placement" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_faq_section_placement";
  CREATE TYPE "public"."enum_pages_blocks_faq_section_placement" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "pages_blocks_faq_section" ALTER COLUMN "placement" SET DATA TYPE "public"."enum_pages_blocks_faq_section_placement" USING "placement"::"public"."enum_pages_blocks_faq_section_placement";
  ALTER TABLE "_pages_v_blocks_faq_section" ALTER COLUMN "placement" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_faq_section_placement";
  CREATE TYPE "public"."enum__pages_v_blocks_faq_section_placement" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "_pages_v_blocks_faq_section" ALTER COLUMN "placement" SET DATA TYPE "public"."enum__pages_v_blocks_faq_section_placement" USING "placement"::"public"."enum__pages_v_blocks_faq_section_placement";
  ALTER TABLE "posts_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_posts_placements";
  CREATE TYPE "public"."enum_posts_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "posts_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_posts_placements" USING "value"::"public"."enum_posts_placements";
  ALTER TABLE "_posts_v_version_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum__posts_v_version_placements";
  CREATE TYPE "public"."enum__posts_v_version_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "_posts_v_version_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum__posts_v_version_placements" USING "value"::"public"."enum__posts_v_version_placements";
  ALTER TABLE "offers_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_offers_placements";
  CREATE TYPE "public"."enum_offers_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "offers_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_offers_placements" USING "value"::"public"."enum_offers_placements";
  ALTER TABLE "_offers_v_version_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum__offers_v_version_placements";
  CREATE TYPE "public"."enum__offers_v_version_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "_offers_v_version_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum__offers_v_version_placements" USING "value"::"public"."enum__offers_v_version_placements";
  ALTER TABLE "reviews_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_reviews_placements";
  CREATE TYPE "public"."enum_reviews_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "reviews_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_reviews_placements" USING "value"::"public"."enum_reviews_placements";
  ALTER TABLE "faqs_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_faqs_placements";
  CREATE TYPE "public"."enum_faqs_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "faqs_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_faqs_placements" USING "value"::"public"."enum_faqs_placements";
  ALTER TABLE "social_responsibility_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_social_responsibility_placements";
  CREATE TYPE "public"."enum_social_responsibility_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "social_responsibility_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_social_responsibility_placements" USING "value"::"public"."enum_social_responsibility_placements";
  ALTER TABLE "team_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_team_placements";
  CREATE TYPE "public"."enum_team_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "team_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_team_placements" USING "value"::"public"."enum_team_placements";
  ALTER TABLE "well_wishers_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_well_wishers_placements";
  CREATE TYPE "public"."enum_well_wishers_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "well_wishers_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_well_wishers_placements" USING "value"::"public"."enum_well_wishers_placements";
  ALTER TABLE "media_placements" ALTER COLUMN "value" SET DATA TYPE text;
  DROP TYPE "public"."enum_media_placements";
  CREATE TYPE "public"."enum_media_placements" AS ENUM('home', 'services', 'our-work', 'contact', 'about', 'production', 'social-media-handling', 'training', 'research', 'it', 'advertisement', 'right-sanchar', 'posts', 'offers');
  ALTER TABLE "media_placements" ALTER COLUMN "value" SET DATA TYPE "public"."enum_media_placements" USING "value"::"public"."enum_media_placements";
  DROP INDEX "payload_locked_documents_rels_social_work_id_idx";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "social_work_id";
  ALTER TABLE "appearance" DROP COLUMN "nepali_font_family";
  ALTER TABLE "appearance" DROP COLUMN "nepali_font_url";
  DROP TYPE "public"."enum_pages_blocks_partner_marquee_tone";
  DROP TYPE "public"."enum__pages_v_blocks_partner_marquee_tone";
  DROP TYPE "public"."enum_social_work_placements";
  DROP TYPE "public"."enum_social_work_status";`)
}
