import Link from "next/link";
import { ArrowRight, BookOpen, Camera, Users } from "lucide-react";
import { servicePortfolio } from "../_data/services";
import { ContactCta, MediaShowcase, PageHero, ProcessSteps, Questions, SectionHeading, ServiceCards } from "../_components/page-content";
import { pageMetadata } from "../_lib/seo";

export const metadata = pageMetadata("Media & Content Creation Training in Nepal", "Explore social media, content creation, journalism, photography, video editing, and creative business training with Najikko Sathi Media in Kathmandu, Nepal.", "/training");

export default function TrainingPage() {
  return <>
    <PageHero eyebrow="Training & capacity building" title="Learn the skills behind meaningful media." description="Practical programs for people who write, report, film, design, and manage digital communication. Start with the skill you want to build." path="/training" label="Training" category="training"><Link className="hero-cta" href="/contact?service=Training">Ask about a program <ArrowRight aria-hidden="true" /></Link></PageHero>
    <section className="content-section"><div className="site-container"><SectionHeading kicker="Learning with purpose" title="Build confidence through practice." description="Training is scoped around the learners, their starting point, and the work they need to do. Individuals, corporate teams, journalists, and creative professionals can discuss a program that fits their goals." /><div className="values-grid">{[{ icon: BookOpen, title: "Understand the fundamentals", text: "Connect the tools with the principles behind clear communication, ethical reporting, and purposeful creative work." }, { icon: Camera, title: "Put ideas into practice", text: "Work through practical exercises in the chosen discipline, using an agreed set of tools and learning objectives." }, { icon: Users, title: "Learn around your needs", text: "Discuss group experience, preferred language, devices, and relevant examples when planning the sessions." }].map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="content-section related-section"><div className="site-container"><SectionHeading kicker="Choose your direction" title="Five programs. Practical possibilities." /><ServiceCards services={servicePortfolio.filter((service) => service.category === "training")} /></div></section>
    <section className="content-section"><div className="site-container"><SectionHeading kicker="Plan a program" title="Start with what you want to be able to do." /><ProcessSteps steps={[["Share your goal", "Tell us the topic, current experience, group size, and preferred learning format."], ["Agree on the program", "Discuss modules, practical requirements, session duration, availability, and fees."], ["Learn and apply", "Use guided exercises to connect the learning with the work you want to create."]]} /></div></section>
    <MediaShowcase mediaKey="training" title="Learning & practice" />
    <section className="content-section"><div className="site-container faq-grid"><SectionHeading kicker="Training questions" title="Make room for learning." /><Questions items={[["Can an organization request team training?", "Yes. Capacity building for corporate teams, journalists, and creative professionals is part of the portfolio. Share the team's responsibilities and learning needs."], ["Are there scheduled batches or certificates?", "A fixed calendar, accreditation, and certification terms are not published here. Contact the team to confirm the current program details before enrolling."], ["How do I choose a program?", "Start with the task you want to perform: managing social pages, creating content, reporting, producing visual work, or developing a creative business idea. The individual program pages explain each scope."]]} /></div></section>
    <ContactCta title="Tell us what you want to learn." service="Training" />
  </>;
}
